apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::586622271145:role/github-runner
      username: github-runner
      groups:
        - deployer-group

