apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8080 # Container port

